version: '3.8'
services:
    colyseus-server:
        container_name: colyseus-server
        build:
            context: ./Server
            dockerfile: Dockerfile

        volumes:
            - ./Server/src:/usr/src/app/src
            - ./Assets/Scripts/Schema:/usr/src/app/client
        ports:
            - 2567:2567
