version: '3.8'
services:
    colyseus-server:
        container_name: colyseus-server
        build:
            context: ./Server
            dockerfile: Dockerfile

        volumes:
            - ./Server/src:/usr/src/app/src
        ports:
            - 8080:8080
